# Generated by Django 4.1.1 on 2022-09-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(default='Auxiliar', max_length=50, verbose_name='Rol'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
