from .userSerializer import UserSerializer
from .psSerializer import PsSerializer
from .personalsaludSerializer import PersonalSaludSerializer
from .signosvitalesSerializer import SignosVitalesSerializer
from .historiaclinicaSerializer import HistoriaClinicaSerializer
from .familiarSerializer import FamiliarSerializer
from .especialidadSerializer import EspecialidadSerializer
from .pacienteSerializer import PacienteSerializer